version: "3.9"
services:
  web:
    build: .
    container_name: flask-huggingface-app
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    volumes:
      - .:/app  # 開発中はローカルを反映したい場合
    restart: always

